export const tableHeads = [
    "Codigo",
    "CI Nombre y Apellidos (Categ. Ocup.)",
    "H. Trab",
    "H. N. Trab",
    "Impunt.",
    "Dias Vac.",
    "Hrs. Certif.",
    "Hrs. Lic. Matern.",
    "Hrs. Resol.",
    "Hrs. Interr.",
    "Otro Tpo a Pagar",
    "Hrs. Extras"
]

export const tableCells = [
    [
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "1"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "Dayli"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "20"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "12"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
    ],
    [
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "2"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "William"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "40"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "3"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
    ],
    [
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "3"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "Popote"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "36"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "15"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
    ],
    [
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "4"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "Mami"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "26"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "8"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
    ],
    [
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "5"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "Alejandra"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "30"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "7"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
    ],
    [
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "6"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "Jose"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "32"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "6"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
    ],
    [
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "7"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "Juan"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "18"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "17"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
    ],
    [
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "8"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "Pedro"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "22"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "9"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
    ],
    [
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "9"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "Pepe"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "35"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "1"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
    ],
    [
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "10"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "Lazaro"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "26"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "10"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
        {isInput: false, colSpan: undefined, type: "", className: undefined, value: "0"},
    ],
]